from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"

rule all:
	input:
		expand("images/{imappart}.svg", imappart=config["imappart"]),

		"index.html"

# Images to include in report
rule get_files4smk_report:
	output:
		part1=report("images/imap_part01.svg", caption="report/software.rst", category="Basic Software"),
		part2=report("images/imap_part02.svg", caption="report/srametadata.rst", category="SRA Metadata Download"),
		part3=report("images/imap_part03.svg", caption="report/srareads.rst", category="SRA FastQ Download"),
		part4=report("images/imap_part04.svg", caption="report/readqc.rst", category="Read QC Analysis"),
		part5=report("images/imap_part05.svg", caption="report/mothur.rst", category="16S-Mothur Analysis"),
		part6=report("images/imap_part06.svg", caption="report/qiime2.rst", category="16S-QIIME2 Analysis"),
		part7=report("images/imap_part07.svg", caption="report/biobakery.rst", category="Metagenomics Analysis"),
		imap=report("images/imap.png", caption="report/imap.rst", category="IMAP Parts"),
	shell:
		"bash workflow/scripts/files4smk_report.sh"



# Get dot rule graphs
rule dot_rules_graph:
	output:
		"dags/rulegraph.svg",
	shell:
		"bash workflow/scripts/rules_dag.sh"


# Get project tree
rule project_tree:
    output:
        tree="results/project_tree.txt",
    shell:
        """
        bash workflow/scripts/tree.sh
        """

# GHPages
rule deploy_to_github_pages:
    output:
        doc="index.html",
    shell:
        """
        R -e "library(rmarkdown); render('index.Rmd')"
        """
