name: microbiome
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
  - anaconda
dependencies:
  - snakemake =7.19.1
  - snakemake-minimal =7.19.1
  - snakemake-wrapper-utils =0.5.0
  - snakedeploy =0.8.6
  - python =3.8.0
  - r-base =4.1.3
  - r-tidyverse =1.3.2 
  - r-bookdown =0.32
  - r-htmltools =0.5.4 
  - r-htmlwidgets =1.6.1
  - r-leaflet =2.1.1
  - r-leaflet.providers =1.9.0 
  - r-rmarkdown =2.20
  - r-schtools =0.4.0
  - graphviz =6.0.1
  - qiime2 =2023.2.0
  - mothur =1.48.0
  - vsearch =2.22.1
  - q2-vsearch =2023.2.0
  - html2image
  - pip =23.0.1